name: fishstiqz
title: fishstiqz 
email: fish@analog.org
tagline: fishstiqz's blog
description: fishstiqz blog computer security 

twitter_username: fishstiqz 
github_username:  fishstiqz 
logo_url: "https://avatars3.githubusercontent.com/u/7143342?s=100"
gpg_fingerprint1: "740F AF32 222C 1863 BDBB"
gpg_fingerprint2: "5EDF 834C CB99 BE29 A971"
gpg_keyfile: "fishstiqz.asc"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fishstiqz.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
